version: "3.7"
services:
  app:
    container_name: nodejs-api-pro
    image: nodeapi:v1
    environment:
           MY_DB: mongodb://mongo_db_host:27017/employeemanagement
    ports:
     - "80:4000"
    depends_on:
     - mongo
    links:
     - mongo:mongo_db_host
  mongo:
    container_name: nodeproject-mongo
    image: mongo